# Generated by Django 4.1.7 on 2023-03-18 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coupon', '0005_student'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaidCoupon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('department', models.CharField(max_length=50)),
                ('meal', models.CharField(max_length=50)),
                ('date', models.DateField()),
            ],
        ),
    ]
